# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menu_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
            ],
            options={
                'verbose_name': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.IntegerField(blank=True, default=0, null=True)),
                ('customization', models.CharField(blank=True, max_length=170, null=True)),
                ('extra_large', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.Employee')),
            ],
            options={
                'verbose_name': 'Employee Order',
            },
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='employee',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
    ]
