# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20170721_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Option'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='employee',
        ),
        migrations.AddField(
            model_name='order',
            name='rut_employee',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
